// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	UserID             int64
	Name               string
	EvaluationStrategy *string
	MaximumScore       *int32
}

type UserAuthProvider struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}

type Violation struct {
	ID                 pgtype.UUID
	UserID             int64
	Type               string
	Description        *string
	Lat                float64
	Lng                float64
	Status             string
	ConfirmationsCount int32
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ViolationPhoto struct {
	ID          pgtype.UUID
	ViolationID pgtype.UUID
	Url         string
	ThumbUrl    *string
}

type ViolationRequest struct {
	ID              pgtype.UUID
	ViolationID     pgtype.UUID
	Status          string
	CreatedByUserID int64
	Comment         *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type ViolationRequestPhoto struct {
	ID        pgtype.UUID
	RequestID pgtype.UUID
	Url       string
	ThumbUrl  *string
	CreatedAt pgtype.Timestamptz
}
