// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddRequestPhoto(ctx context.Context, arg *AddRequestPhotoParams) (*ViolationRequestPhoto, error)
	AddUserAuthProviders(ctx context.Context, arg *AddUserAuthProvidersParams) (*UserAuthProvider, error)
	AddViolationPhoto(ctx context.Context, arg *AddViolationPhotoParams) (*ViolationPhoto, error)
	CountViolations(ctx context.Context, arg *CountViolationsParams) (int64, error)
	CreateUser(ctx context.Context, name string) (int64, error)
	// Violations
	CreateViolation(ctx context.Context, arg *CreateViolationParams) (*Violation, error)
	// Violation chat messages
	CreateViolationChatMessage(ctx context.Context, arg *CreateViolationChatMessageParams) (*ViolationChatMessage, error)
	// Violation complaints
	CreateViolationComplaint(ctx context.Context, arg *CreateViolationComplaintParams) (*ViolationComplaint, error)
	// Violation Requests
	CreateViolationRequest(ctx context.Context, arg *CreateViolationRequestParams) (*ViolationRequest, error)
	CreateViolationRequestComplaint(ctx context.Context, arg *CreateViolationRequestComplaintParams) (*ViolationComplaint, error)
	DeleteUserAuthProvider(ctx context.Context, arg *DeleteUserAuthProviderParams) error
	DeleteViolationChatMessage(ctx context.Context, arg *DeleteViolationChatMessageParams) (pgtype.UUID, error)
	DeleteViolationVote(ctx context.Context, arg *DeleteViolationVoteParams) error
	GetPhotosByViolationID(ctx context.Context, violationID pgtype.UUID) ([]*ViolationPhoto, error)
	GetRequestPhotosByRequestID(ctx context.Context, requestID pgtype.UUID) ([]*ViolationRequestPhoto, error)
	GetUserAuthProvidersByProviderUid(ctx context.Context, arg *GetUserAuthProvidersByProviderUidParams) (*UserAuthProvider, error)
	GetUserAuthProvidersByUserID(ctx context.Context, userID int64) ([]*UserAuthProvider, error)
	GetUserByID(ctx context.Context, userID int64) (*User, error)
	GetUsersByIDs(ctx context.Context, dollar_1 []int64) ([]*User, error)
	GetViolationByID(ctx context.Context, id pgtype.UUID) (*Violation, error)
	GetViolationRequestByID(ctx context.Context, id pgtype.UUID) (*ViolationRequest, error)
	GetViolationRequestsByViolationID(ctx context.Context, violationID pgtype.UUID) ([]*GetViolationRequestsByViolationIDRow, error)
	GetViolationVotesAggregated(ctx context.Context, arg *GetViolationVotesAggregatedParams) (*GetViolationVotesAggregatedRow, error)
	ListViolationChatMessages(ctx context.Context, arg *ListViolationChatMessagesParams) ([]*ViolationChatMessage, error)
	ListViolations(ctx context.Context, arg *ListViolationsParams) ([]*Violation, error)
	SetUserAvatarIfEmpty(ctx context.Context, arg *SetUserAvatarIfEmptyParams) error
	UpdateUserAvatar(ctx context.Context, arg *UpdateUserAvatarParams) error
	UpdateUserBoostyURL(ctx context.Context, arg *UpdateUserBoostyURLParams) error
	UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error)
	UpdateViolationChatMessage(ctx context.Context, arg *UpdateViolationChatMessageParams) (*ViolationChatMessage, error)
	UpdateViolationStatus(ctx context.Context, arg *UpdateViolationStatusParams) (*Violation, error)
	UpsertViolationRequestVote(ctx context.Context, arg *UpsertViolationRequestVoteParams) (*ViolationVote, error)
	// Violation votes
	UpsertViolationVote(ctx context.Context, arg *UpsertViolationVoteParams) (*ViolationVote, error)
}

var _ Querier = (*Queries)(nil)
