// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc_repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRequestPhoto = `-- name: AddRequestPhoto :one
INSERT INTO violation_request_photos (id, request_id, url, thumb_url)
VALUES ($1, $2, $3, $4)
RETURNING id, request_id, url, thumb_url, created_at
`

type AddRequestPhotoParams struct {
	ID        pgtype.UUID
	RequestID pgtype.UUID
	Url       string
	ThumbUrl  *string
}

func (q *Queries) AddRequestPhoto(ctx context.Context, arg *AddRequestPhotoParams) (*ViolationRequestPhoto, error) {
	row := q.db.QueryRow(ctx, addRequestPhoto,
		arg.ID,
		arg.RequestID,
		arg.Url,
		arg.ThumbUrl,
	)
	var i ViolationRequestPhoto
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Url,
		&i.ThumbUrl,
		&i.CreatedAt,
	)
	return &i, err
}

const addUserAuthProviders = `-- name: AddUserAuthProviders :one
INSERT INTO user_auth_providers (user_id, provider_uid, provider, name)
VALUES ($1, $2, $3, $4)
returning user_id, provider_uid, provider, name
`

type AddUserAuthProvidersParams struct {
	UserID      int64
	ProviderUid string
	Provider    string
	Name        *string
}

func (q *Queries) AddUserAuthProviders(ctx context.Context, arg *AddUserAuthProvidersParams) (*UserAuthProvider, error) {
	row := q.db.QueryRow(ctx, addUserAuthProviders,
		arg.UserID,
		arg.ProviderUid,
		arg.Provider,
		arg.Name,
	)
	var i UserAuthProvider
	err := row.Scan(
		&i.UserID,
		&i.ProviderUid,
		&i.Provider,
		&i.Name,
	)
	return &i, err
}

const addViolationPhoto = `-- name: AddViolationPhoto :one
INSERT INTO violation_photos (id, violation_id, url, thumb_url)
VALUES ($1, $2, $3, $4)
RETURNING id, violation_id, url, thumb_url
`

type AddViolationPhotoParams struct {
	ID          pgtype.UUID
	ViolationID pgtype.UUID
	Url         string
	ThumbUrl    *string
}

func (q *Queries) AddViolationPhoto(ctx context.Context, arg *AddViolationPhotoParams) (*ViolationPhoto, error) {
	row := q.db.QueryRow(ctx, addViolationPhoto,
		arg.ID,
		arg.ViolationID,
		arg.Url,
		arg.ThumbUrl,
	)
	var i ViolationPhoto
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.Url,
		&i.ThumbUrl,
	)
	return &i, err
}

const countViolations = `-- name: CountViolations :one
SELECT count(1)
FROM violations
WHERE
  ($1::text IS NULL OR type = $1) AND
  ($2::text IS NULL OR status = $2) AND
  ($3::timestamptz IS NULL OR created_at >= $3) AND
  ($4::timestamptz IS NULL OR created_at <= $4) AND
  (
    ($5::float8 IS NULL OR $6::float8 IS NULL OR $7::float8 IS NULL OR $8::float8 IS NULL)
    OR (lng BETWEEN $5 AND $7 AND lat BETWEEN $6 AND $8)
  )
`

type CountViolationsParams struct {
	Column1 string
	Column2 string
	Column3 pgtype.Timestamptz
	Column4 pgtype.Timestamptz
	Column5 float64
	Column6 float64
	Column7 float64
	Column8 float64
}

func (q *Queries) CountViolations(ctx context.Context, arg *CountViolationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countViolations,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name)
VALUES ($1)
returning user_id
`

func (q *Queries) CreateUser(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, createUser, name)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createViolation = `-- name: CreateViolation :one

INSERT INTO violations (id, user_id, type, description, lat, lng, status, confirmations_count)
VALUES ($1, $2, $3, $4, $5, $6, 'new', 0)
RETURNING id, user_id, type, description, lat, lng, status, confirmations_count, created_at, updated_at
`

type CreateViolationParams struct {
	ID          pgtype.UUID
	UserID      int64
	Type        string
	Description *string
	Lat         float64
	Lng         float64
}

// Violations
func (q *Queries) CreateViolation(ctx context.Context, arg *CreateViolationParams) (*Violation, error) {
	row := q.db.QueryRow(ctx, createViolation,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.Description,
		arg.Lat,
		arg.Lng,
	)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.ConfirmationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createViolationChatMessage = `-- name: CreateViolationChatMessage :one

INSERT INTO violation_chat_messages (id, violation_id, user_id, text, is_system)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, violation_id, user_id, text, is_system, created_at, updated_at
`

type CreateViolationChatMessageParams struct {
	ID          pgtype.UUID
	ViolationID pgtype.UUID
	UserID      int64
	Text        string
	IsSystem    bool
}

// Violation chat messages
func (q *Queries) CreateViolationChatMessage(ctx context.Context, arg *CreateViolationChatMessageParams) (*ViolationChatMessage, error) {
	row := q.db.QueryRow(ctx, createViolationChatMessage,
		arg.ID,
		arg.ViolationID,
		arg.UserID,
		arg.Text,
		arg.IsSystem,
	)
	var i ViolationChatMessage
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.UserID,
		&i.Text,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createViolationComplaint = `-- name: CreateViolationComplaint :one

INSERT INTO violation_complaints (id, violation_id, user_id, reason, message)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, violation_id, request_id, user_id, reason, message, created_at
`

type CreateViolationComplaintParams struct {
	ID          pgtype.UUID
	ViolationID pgtype.UUID
	UserID      int64
	Reason      *string
	Message     *string
}

// Violation complaints
func (q *Queries) CreateViolationComplaint(ctx context.Context, arg *CreateViolationComplaintParams) (*ViolationComplaint, error) {
	row := q.db.QueryRow(ctx, createViolationComplaint,
		arg.ID,
		arg.ViolationID,
		arg.UserID,
		arg.Reason,
		arg.Message,
	)
	var i ViolationComplaint
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.RequestID,
		&i.UserID,
		&i.Reason,
		&i.Message,
		&i.CreatedAt,
	)
	return &i, err
}

const createViolationRequest = `-- name: CreateViolationRequest :one

INSERT INTO violation_requests (id, violation_id, status, created_by_user_id, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, violation_id, status, created_by_user_id, comment, created_at, updated_at
`

type CreateViolationRequestParams struct {
	ID              pgtype.UUID
	ViolationID     pgtype.UUID
	Status          string
	CreatedByUserID int64
	Comment         *string
}

// Violation Requests
func (q *Queries) CreateViolationRequest(ctx context.Context, arg *CreateViolationRequestParams) (*ViolationRequest, error) {
	row := q.db.QueryRow(ctx, createViolationRequest,
		arg.ID,
		arg.ViolationID,
		arg.Status,
		arg.CreatedByUserID,
		arg.Comment,
	)
	var i ViolationRequest
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.Status,
		&i.CreatedByUserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const createViolationRequestComplaint = `-- name: CreateViolationRequestComplaint :one
INSERT INTO violation_complaints (id, violation_id, request_id, user_id, reason, message)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, violation_id, request_id, user_id, reason, message, created_at
`

type CreateViolationRequestComplaintParams struct {
	ID          pgtype.UUID
	ViolationID pgtype.UUID
	RequestID   pgtype.UUID
	UserID      int64
	Reason      *string
	Message     *string
}

func (q *Queries) CreateViolationRequestComplaint(ctx context.Context, arg *CreateViolationRequestComplaintParams) (*ViolationComplaint, error) {
	row := q.db.QueryRow(ctx, createViolationRequestComplaint,
		arg.ID,
		arg.ViolationID,
		arg.RequestID,
		arg.UserID,
		arg.Reason,
		arg.Message,
	)
	var i ViolationComplaint
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.RequestID,
		&i.UserID,
		&i.Reason,
		&i.Message,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteUserAuthProvider = `-- name: DeleteUserAuthProvider :exec
DELETE FROM user_auth_providers
WHERE user_id = $1 AND provider = $2
`

type DeleteUserAuthProviderParams struct {
	UserID   int64
	Provider string
}

func (q *Queries) DeleteUserAuthProvider(ctx context.Context, arg *DeleteUserAuthProviderParams) error {
	_, err := q.db.Exec(ctx, deleteUserAuthProvider, arg.UserID, arg.Provider)
	return err
}

const deleteViolationChatMessage = `-- name: DeleteViolationChatMessage :one
DELETE FROM violation_chat_messages
WHERE id = $1 AND user_id = $2 AND is_system = FALSE
RETURNING violation_id
`

type DeleteViolationChatMessageParams struct {
	ID     pgtype.UUID
	UserID int64
}

func (q *Queries) DeleteViolationChatMessage(ctx context.Context, arg *DeleteViolationChatMessageParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteViolationChatMessage, arg.ID, arg.UserID)
	var violation_id pgtype.UUID
	err := row.Scan(&violation_id)
	return violation_id, err
}

const deleteViolationVote = `-- name: DeleteViolationVote :exec
DELETE FROM violation_votes
WHERE violation_id = $1 AND user_id = $2
`

type DeleteViolationVoteParams struct {
	ViolationID pgtype.UUID
	UserID      int64
}

func (q *Queries) DeleteViolationVote(ctx context.Context, arg *DeleteViolationVoteParams) error {
	_, err := q.db.Exec(ctx, deleteViolationVote, arg.ViolationID, arg.UserID)
	return err
}

const getPhotosByViolationID = `-- name: GetPhotosByViolationID :many
SELECT id, violation_id, url, thumb_url FROM violation_photos WHERE violation_id = $1 ORDER BY id
`

func (q *Queries) GetPhotosByViolationID(ctx context.Context, violationID pgtype.UUID) ([]*ViolationPhoto, error) {
	rows, err := q.db.Query(ctx, getPhotosByViolationID, violationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ViolationPhoto
	for rows.Next() {
		var i ViolationPhoto
		if err := rows.Scan(
			&i.ID,
			&i.ViolationID,
			&i.Url,
			&i.ThumbUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestPhotosByRequestID = `-- name: GetRequestPhotosByRequestID :many
SELECT id, request_id, url, thumb_url, created_at FROM violation_request_photos WHERE request_id = $1 ORDER BY created_at
`

func (q *Queries) GetRequestPhotosByRequestID(ctx context.Context, requestID pgtype.UUID) ([]*ViolationRequestPhoto, error) {
	rows, err := q.db.Query(ctx, getRequestPhotosByRequestID, requestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ViolationRequestPhoto
	for rows.Next() {
		var i ViolationRequestPhoto
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Url,
			&i.ThumbUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAuthProvidersByProviderUid = `-- name: GetUserAuthProvidersByProviderUid :one
SELECT user_id, provider_uid, provider, name FROM user_auth_providers
WHERE provider_uid = $1 AND provider = $2
`

type GetUserAuthProvidersByProviderUidParams struct {
	ProviderUid string
	Provider    string
}

func (q *Queries) GetUserAuthProvidersByProviderUid(ctx context.Context, arg *GetUserAuthProvidersByProviderUidParams) (*UserAuthProvider, error) {
	row := q.db.QueryRow(ctx, getUserAuthProvidersByProviderUid, arg.ProviderUid, arg.Provider)
	var i UserAuthProvider
	err := row.Scan(
		&i.UserID,
		&i.ProviderUid,
		&i.Provider,
		&i.Name,
	)
	return &i, err
}

const getUserAuthProvidersByUserID = `-- name: GetUserAuthProvidersByUserID :many
SELECT user_id, provider_uid, provider, name FROM user_auth_providers
WHERE user_id = $1
`

func (q *Queries) GetUserAuthProvidersByUserID(ctx context.Context, userID int64) ([]*UserAuthProvider, error) {
	rows, err := q.db.Query(ctx, getUserAuthProvidersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserAuthProvider
	for rows.Next() {
		var i UserAuthProvider
		if err := rows.Scan(
			&i.UserID,
			&i.ProviderUid,
			&i.Provider,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, name, evaluation_strategy, maximum_score, avatar_url, boosty_url FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID int64) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.EvaluationStrategy,
		&i.MaximumScore,
		&i.AvatarUrl,
		&i.BoostyUrl,
	)
	return &i, err
}

const getUsersByIDs = `-- name: GetUsersByIDs :many
SELECT user_id, name, evaluation_strategy, maximum_score, avatar_url, boosty_url FROM users
WHERE user_id = ANY($1::bigint[])
`

func (q *Queries) GetUsersByIDs(ctx context.Context, dollar_1 []int64) ([]*User, error) {
	rows, err := q.db.Query(ctx, getUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.EvaluationStrategy,
			&i.MaximumScore,
			&i.AvatarUrl,
			&i.BoostyUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getViolationByID = `-- name: GetViolationByID :one
SELECT id, user_id, type, description, lat, lng, status, confirmations_count, created_at, updated_at FROM violations WHERE id = $1
`

func (q *Queries) GetViolationByID(ctx context.Context, id pgtype.UUID) (*Violation, error) {
	row := q.db.QueryRow(ctx, getViolationByID, id)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.ConfirmationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getViolationRequestByID = `-- name: GetViolationRequestByID :one
SELECT id, violation_id, status, created_by_user_id, comment, created_at, updated_at FROM violation_requests WHERE id = $1
`

func (q *Queries) GetViolationRequestByID(ctx context.Context, id pgtype.UUID) (*ViolationRequest, error) {
	row := q.db.QueryRow(ctx, getViolationRequestByID, id)
	var i ViolationRequest
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.Status,
		&i.CreatedByUserID,
		&i.Comment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getViolationRequestsByViolationID = `-- name: GetViolationRequestsByViolationID :many
SELECT
  vr.id,
  vr.violation_id,
  vr.status,
  vr.created_by_user_id,
  vr.comment,
  vr.created_at,
  vr.updated_at,
  u.boosty_url AS author_boosty_url,
  u.avatar_url AS author_avatar_url
FROM violation_requests vr
LEFT JOIN users u ON vr.created_by_user_id = u.user_id
WHERE vr.violation_id = $1
ORDER BY vr.created_at
`

type GetViolationRequestsByViolationIDRow struct {
	ID              pgtype.UUID
	ViolationID     pgtype.UUID
	Status          string
	CreatedByUserID int64
	Comment         *string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	AuthorBoostyUrl *string
	AuthorAvatarUrl *string
}

func (q *Queries) GetViolationRequestsByViolationID(ctx context.Context, violationID pgtype.UUID) ([]*GetViolationRequestsByViolationIDRow, error) {
	rows, err := q.db.Query(ctx, getViolationRequestsByViolationID, violationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetViolationRequestsByViolationIDRow
	for rows.Next() {
		var i GetViolationRequestsByViolationIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ViolationID,
			&i.Status,
			&i.CreatedByUserID,
			&i.Comment,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AuthorBoostyUrl,
			&i.AuthorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getViolationVotesAggregated = `-- name: GetViolationVotesAggregated :one
SELECT
    violation_id,
    COALESCE(sum(CASE WHEN value = 'like' THEN 1 ELSE 0 END), 0)   AS likes,
    COALESCE(sum(CASE WHEN value = 'dislike' THEN 1 ELSE 0 END), 0) AS dislikes,
    COALESCE(
        max(
            CASE
                WHEN user_id = $2 THEN value
                ELSE NULL
            END
        ),
        ''
    ) AS user_vote
FROM violation_votes
WHERE violation_id = $1
GROUP BY violation_id
`

type GetViolationVotesAggregatedParams struct {
	ViolationID pgtype.UUID
	UserID      int64
}

type GetViolationVotesAggregatedRow struct {
	ViolationID pgtype.UUID
	Likes       interface{}
	Dislikes    interface{}
	UserVote    interface{}
}

func (q *Queries) GetViolationVotesAggregated(ctx context.Context, arg *GetViolationVotesAggregatedParams) (*GetViolationVotesAggregatedRow, error) {
	row := q.db.QueryRow(ctx, getViolationVotesAggregated, arg.ViolationID, arg.UserID)
	var i GetViolationVotesAggregatedRow
	err := row.Scan(
		&i.ViolationID,
		&i.Likes,
		&i.Dislikes,
		&i.UserVote,
	)
	return &i, err
}

const listViolationChatMessages = `-- name: ListViolationChatMessages :many
SELECT id, violation_id, user_id, text, is_system, created_at, updated_at
FROM violation_chat_messages
WHERE violation_id = $1
ORDER BY created_at ASC, id ASC
LIMIT $2 OFFSET $3
`

type ListViolationChatMessagesParams struct {
	ViolationID pgtype.UUID
	Limit       int32
	Offset      int32
}

func (q *Queries) ListViolationChatMessages(ctx context.Context, arg *ListViolationChatMessagesParams) ([]*ViolationChatMessage, error) {
	rows, err := q.db.Query(ctx, listViolationChatMessages, arg.ViolationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ViolationChatMessage
	for rows.Next() {
		var i ViolationChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ViolationID,
			&i.UserID,
			&i.Text,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViolations = `-- name: ListViolations :many
SELECT id, user_id, type, description, lat, lng, status, confirmations_count, created_at, updated_at
FROM violations
WHERE
  ($1::text IS NULL OR type = $1) AND
  ($2::text IS NULL OR status = $2) AND
  ($3::timestamptz IS NULL OR created_at >= $3) AND
  ($4::timestamptz IS NULL OR created_at <= $4) AND
  (
    ($5::float8 IS NULL OR $6::float8 IS NULL OR $7::float8 IS NULL OR $8::float8 IS NULL)
    OR (lng BETWEEN $5 AND $7 AND lat BETWEEN $6 AND $8)
  )
ORDER BY created_at DESC
LIMIT $9 OFFSET $10
`

type ListViolationsParams struct {
	Column1 string
	Column2 string
	Column3 pgtype.Timestamptz
	Column4 pgtype.Timestamptz
	Column5 float64
	Column6 float64
	Column7 float64
	Column8 float64
	Limit   int32
	Offset  int32
}

func (q *Queries) ListViolations(ctx context.Context, arg *ListViolationsParams) ([]*Violation, error) {
	rows, err := q.db.Query(ctx, listViolations,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Column8,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Violation
	for rows.Next() {
		var i Violation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Description,
			&i.Lat,
			&i.Lng,
			&i.Status,
			&i.ConfirmationsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAvatarIfEmpty = `-- name: SetUserAvatarIfEmpty :exec
UPDATE users
SET avatar_url = $2
WHERE user_id = $1 AND (avatar_url IS NULL OR avatar_url = '')
`

type SetUserAvatarIfEmptyParams struct {
	UserID    int64
	AvatarUrl *string
}

func (q *Queries) SetUserAvatarIfEmpty(ctx context.Context, arg *SetUserAvatarIfEmptyParams) error {
	_, err := q.db.Exec(ctx, setUserAvatarIfEmpty, arg.UserID, arg.AvatarUrl)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_url = $2
WHERE user_id = $1
`

type UpdateUserAvatarParams struct {
	UserID    int64
	AvatarUrl *string
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg *UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.UserID, arg.AvatarUrl)
	return err
}

const updateUserBoostyURL = `-- name: UpdateUserBoostyURL :exec
UPDATE users
SET boosty_url = $2
WHERE user_id = $1
`

type UpdateUserBoostyURLParams struct {
	UserID    int64
	BoostyUrl *string
}

func (q *Queries) UpdateUserBoostyURL(ctx context.Context, arg *UpdateUserBoostyURLParams) error {
	_, err := q.db.Exec(ctx, updateUserBoostyURL, arg.UserID, arg.BoostyUrl)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users
SET name = $1
WHERE user_id = $2
RETURNING user_id, name, evaluation_strategy, maximum_score, avatar_url, boosty_url
`

type UpdateUserNameParams struct {
	Name   string
	UserID int64
}

func (q *Queries) UpdateUserName(ctx context.Context, arg *UpdateUserNameParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.Name, arg.UserID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.EvaluationStrategy,
		&i.MaximumScore,
		&i.AvatarUrl,
		&i.BoostyUrl,
	)
	return &i, err
}

const updateViolationChatMessage = `-- name: UpdateViolationChatMessage :one
UPDATE violation_chat_messages
SET text = $1, updated_at = NOW()
WHERE id = $2 AND user_id = $3 AND is_system = FALSE
RETURNING id, violation_id, user_id, text, is_system, created_at, updated_at
`

type UpdateViolationChatMessageParams struct {
	Text   string
	ID     pgtype.UUID
	UserID int64
}

func (q *Queries) UpdateViolationChatMessage(ctx context.Context, arg *UpdateViolationChatMessageParams) (*ViolationChatMessage, error) {
	row := q.db.QueryRow(ctx, updateViolationChatMessage, arg.Text, arg.ID, arg.UserID)
	var i ViolationChatMessage
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.UserID,
		&i.Text,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateViolationStatus = `-- name: UpdateViolationStatus :one
UPDATE violations
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, type, description, lat, lng, status, confirmations_count, created_at, updated_at
`

type UpdateViolationStatusParams struct {
	ID     pgtype.UUID
	Status string
}

func (q *Queries) UpdateViolationStatus(ctx context.Context, arg *UpdateViolationStatusParams) (*Violation, error) {
	row := q.db.QueryRow(ctx, updateViolationStatus, arg.ID, arg.Status)
	var i Violation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Description,
		&i.Lat,
		&i.Lng,
		&i.Status,
		&i.ConfirmationsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertViolationRequestVote = `-- name: UpsertViolationRequestVote :one
INSERT INTO violation_votes (id, violation_id, request_id, user_id, value)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (request_id, user_id) DO UPDATE
SET value = EXCLUDED.value,
    updated_at = NOW(),
    request_id = EXCLUDED.request_id
RETURNING id, violation_id, request_id, user_id, value, created_at, updated_at
`

type UpsertViolationRequestVoteParams struct {
	ID          pgtype.UUID
	ViolationID pgtype.UUID
	RequestID   pgtype.UUID
	UserID      int64
	Value       string
}

func (q *Queries) UpsertViolationRequestVote(ctx context.Context, arg *UpsertViolationRequestVoteParams) (*ViolationVote, error) {
	row := q.db.QueryRow(ctx, upsertViolationRequestVote,
		arg.ID,
		arg.ViolationID,
		arg.RequestID,
		arg.UserID,
		arg.Value,
	)
	var i ViolationVote
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.RequestID,
		&i.UserID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const upsertViolationVote = `-- name: UpsertViolationVote :one

INSERT INTO violation_votes (id, violation_id, user_id, value)
VALUES ($1, $2, $3, $4)
ON CONFLICT (violation_id, user_id) DO UPDATE
SET value = EXCLUDED.value, updated_at = NOW()
RETURNING id, violation_id, request_id, user_id, value, created_at, updated_at
`

type UpsertViolationVoteParams struct {
	ID          pgtype.UUID
	ViolationID pgtype.UUID
	UserID      int64
	Value       string
}

// Violation votes
func (q *Queries) UpsertViolationVote(ctx context.Context, arg *UpsertViolationVoteParams) (*ViolationVote, error) {
	row := q.db.QueryRow(ctx, upsertViolationVote,
		arg.ID,
		arg.ViolationID,
		arg.UserID,
		arg.Value,
	)
	var i ViolationVote
	err := row.Scan(
		&i.ID,
		&i.ViolationID,
		&i.RequestID,
		&i.UserID,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
